name: CI Test

on:
  push:
    branches: [ 'bug/*', 'feature/*' ]

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests..."
          npm install
          npm test

      - name: Intentional failure for testing
        run: exit 1
