name: Deploy → Staging

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:

  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install

      - run: npm test -- --coverage --coverageReporters=lcov text

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-staging
          path: coverage/

  deploy:
    name: Deploy → Staging
    runs-on: self-hosted
    needs: test

    environment:
      name: staging
      url: http://localhost:8081

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging..."
          docker cp app/. devops_staging:/usr/share/nginx/html/
          docker exec devops_staging nginx -s reload
